server:
  port: ${PORT:8080}

spring:
  application:
    name: EBANX Take Home Assignment

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop

    properties:
      javax:

    show-sql: true

  h2:
    console.enabled: true